### ISSUE TITLE
cpptraj/pytraj todolist

### ISSUE THREAD

**Issue by hainm** [mojyt/cpptraj#10]
I create this issue here to take note of new codes/features should be in cpptraj for pytraj's convenience. Hopefully Dan does not mind.

### CpptrajState.h
add `GetTrajinList()`, `GetActionList()`, `GetAnalysisList()`, `GetTrajoutList`

**Comment by hainm** [comment]
Add more constructor for cpptraj's Frame class
Frame(int n_atoms, double* ptr)

    Frame::Frame(int natomIn, double* ptr) :
      natom_(natomIn),
      maxnatom_(natomIn),
      ncoord_(natomIn*3), 
      T_(0.0),
      time_(0.0),
      X_(0),
      V_(0),
      Mass_(natomIn, 1.0)
    {
      if (ncoord_ > 0)
        X_ = ptr;
    }

This is really convenient for pytraj to expose 3D array xyz coords of Traj to numpy without data copying.

Currently, pytraj has FrameArray (which is a wrapper of vector of Frame objects, calling frame_array_obj.xyz will return a `copy` of 3D numpy array (n_xyz). This means if updating n_xyz, frame_array_obj is not updated.

I am thinking about constructing FrameArray (FA) in different way in future. Rather than being a wrapper of vector of Frame objects, FA will be simply just a wrapper of 1D array (name `arr0`) (length = `n_frames * n_atoms * 3`.  Indexing frame_array_obj like `frame_array_obj[idx]` will return a Frame object which is just a view of a chunk of memory block (from constructor `Frame(n_atoms, &arr0[3*n_atoms*idx]`)

**Comment by hainm** [comment]
I actually just give a test for above idea (in Amber `pytraj_framearray_memview` branch).

If there is anyone ever curious about this, should look at: 

    $AMBERHOME/AmberTools/src/pytraj/pytraj/FrameArray_2.pyx

This is the test:$AMBERHOME/AmberTools/src/pytraj/tests/test_FrameArray_2_memview.py

    from __future__ import print_function
    import unittest
    from pytraj.base import *
    from pytraj import adict
    from pytraj import io as mdio
    from pytraj.utils.check_and_assert import assert_almost_equal
    from pytraj.decorators import no_test, test_if_having

    class Test(unittest.TestCase):
        @test_if_having("numpy")
        def test_0(self):
            import numpy as np
            from pytraj.FrameArray_2 import FrameArray_2
            # load regular pytraj Trajectory object (in AmberTools 15)
            traj = mdio.load("./data/md1_prod.Tc5b.x", "./data/Tc5b.top")

            fa = FrameArray_2() # my new experience
            fa.top = traj.top.copy()
            for frame in traj:
                fa.append(frame)

            assert fa.n_frames == traj.n_frames

            xyz = np.asarray(fa.buffer1d).reshape((fa.n_frames, fa.top.n_atoms, 3))
            xyz[0, 0, 0] = 1000.
            print (fa.xyz[0, 0, 0])

            new_x = 2000.
            fa.xyz[9, 0, 0]= new_x
        
            # update fa.xyz will also update `xyz` numpy array
            assert fa.xyz[9, 0, 0] == new_x
            assert xyz[9, 0, 0] == new_x

    if __name__ == "__main__":
        unittest.main()

**Comment by hainm** [comment]
# Reorganize cpptraj folders

Something like
cpptraj:
    *  Core
    * Clusters
    * Actions
    * Analyses
    * DataSets

**Comment by hainm** [comment]
### list of Actions that should dump data to DataSetList
(will be added more). 

`Disclaimer: Since I am not really good at C++, I might misunderstood cpptraj's code.`
* Action_Density
* Action_OrderParameter
*

**Comment by mojyt** [comment]
Hai,

You and I should probably talk more about a few of these. I've created and shared a google doc with you and Jason which I think will be a better, more interactive medium for discussing these. Let me know if you don't get the link.
