### ISSUE TITLE
Inside DataSetList.cpp reference to non-existent file in repo

### ISSUE THREAD

**Issue by DeBeNoPrMa** [mojyt/cpptraj#4]
Hello!

Inside DataSetList.cpp there's a reference to DataSet_Coords_REF.h (#include "DataSet_Coords_REF.h") in line 23 but there's no such file in the repository. I guess it's a recent addition and hasn't been created or added.

**Comment by hainm** [comment]
Just want to add one more comment: it is really great if Dan can include travis built status in README file.

**Comment by swails** [comment]
On Fri, 2015-01-30 at 07:36 -0800, Hai Nguyen wrote:
> Just want to add one more comment: it is really great if Dan can
> include travis built status in README file.

Submit a PR for it ;).  He'll merge it.


-- 
Jason M. Swails
BioMaPS,
Rutgers University
Postdoctoral Researcher

**Comment by hainm** [comment]
Ah, right. I bet i am still new to git.

**Comment by mojyt** [comment]
Apologies, I had forgotten to add a few files yesterday (big commit). Files have been added and build now passes - let me know if you see any other issues. Thanks!
