### ISSUE TITLE
vmd style for atom selection? 

### ISSUE THREAD

**Issue by hainm** [mojyt/cpptraj#6]
hi @swails @mojyt 

what do you guys think about adding AtomMask parsing like vmd style? ("water and CA", ...) into cpptraj/pytraj/ParmEd? I guess both of you already though about this and there must a reason not to do this in AMBER (much more concise syntax?).

Hai

**Comment by swails** [comment]
Complexity, IMO.  This is a complex parser to write.  MDTraj has it in Python (and I'm thinking about pilfering it for ParmEd).

The reason *I* haven't done it for ParmEd yet is because my time is limited and its priority is much lower than other improvements I want to make.  Given that the Amber mask is just as expressive (albeit with a steeper learning curve and more obfuscated syntax), the priority to add this is even lower.

My guess is @mojyt's reason is similar, and *he* probably doesn't have as convenient a place to steal a parser as I do... (unless VMD has a modular version of it and their license is suitably permissive enough to steal the code).

**Comment by hainm** [comment]
ha ha, I guess I would "steal" from either mdtraj or other open sources. cpptraj can still benefit from this via pytraj. :D (and it makes sense to not reinvent the wheel).

**Comment by mojyt** [comment]
On Saturday, February 7, 2015, Hai Nguyen <notifications@github.com> wrote:

> (and it makes sense to not reinvent the wheel).
>
This is the main reason for me.  The current mask parser works just fine,
so there is little incentive to put much work into this right now. I would
like to eventually support keywords like 'backbone' etc, but that brings
additional complexities (e.g. Backbone atom names differ between different
md packages). May be something to chat about at the Amber mtg.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/6#issuecomment-73393734>.
>


-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
> I would
> like to eventually support keywords like 'backbone' etc, but that brings
> additional complexities (e.g. Backbone atom names differ between different
> md packages).

Are you thinking as a separate grammar supported by cpptraj, or as an extension to the Amber mask syntax? (Just out of curiosity)

**Comment by mojyt** [comment]
On Sun, Feb 8, 2015 at 2:00 PM, Jason Swails <notifications@github.com>
wrote:

> I would
> like to eventually support keywords like 'backbone' etc, but that brings
> additional complexities (e.g. Backbone atom names differ between different
> md packages).
>
> Are you thinking as a separate grammar supported by cpptraj, or as an
> extension to the Amber mask syntax? (Just out of curiosity)
>

The former to start (if it ever happens at all). I don't want to mess with
any of the other masks parsers for experimental stuff (also fortran makes
my head ache sometimes).

-Dan


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/6#issuecomment-73431485>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)
