### ISSUE TITLE
sync with Amber master?

### ISSUE THREAD

**Issue by hainm** [mojyt/cpptraj#8]
Hi @mojyt 

can you please sync github version with Amber master? I guess you made significantly changed (like Trajout class, ...) but have not seen in github yet. I need to follow your change too.

Hai

**Comment by hainm** [comment]
@mojyt: need to update libcpptraj in master too.

**Comment by mojyt** [comment]
Hi,

Sorry for the delay, I've been travelling.

I will update github as soon as I can - I'm not too familiar with subtree
yet though so worst case scenario I do a big meld. That may take some time
though. Hope to have it done between today and tomorrow.

-Dan

On Wed, Mar 4, 2015 at 1:16 PM, Hai Nguyen <notifications@github.com> wrote:

> @mojyt <https://github.com/mojyt>: need to update libcpptraj in master
> too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojyt/cpptraj/issues/8#issuecomment-77237278>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
hi @mojyt 

take your time. I've just make pytraj's changes following your changes in Amber master. You can do it when you have free time. But what I really need is to update configure file and Makefile in Amber master. (I made changes for cpptraj in remotes/origin/pytraj2 though). I am a bit rush since the deadline for Ambertools is this Friday (and I just realized I need to update pytraj :D, but things are fine now). thanks.

Hai
